pipeline:
  publish:
    image: appleboy/drone-scp
    settings:
      host: 
        from_secret: jupiterIP
      username: camille
      key: 
        from_secret: DOPrivateKey
      target: /home/www/docker
      source: .
      overwrite: true
      
  restart:
    image: appleboy/drone-ssh
    settings:
      host: 
        from_secret: jupiterIP
      username: camille
      key: 
        from_secret: DOPrivateKey
      script:
        - docker restart quotes
branches: master
